name: PHP Unit Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    php

    steps:
    with:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      php-version: 7.4
      run: composer validate --strict

    - name: Cache Composer packages
      php-version: 7.4
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      php-version: 7.4
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      php-version: 7.4
      run: composer run-script test
